version: '3'
services:
  koth:
    image: koth
    ports:
      - "8081:8081"
    environment: 
      - EXT_SECRET=$EXT_SECRET
      - EXT_CLIENT_ID=$EXT_CLIENT_ID
      - EXT_OWNER_ID=$EXT_OWNER_ID
  nginx:
    image: nginx:1.15-alpine
    ports:
      - "80:80"
      - "443:443"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - ./conf:/etc/koth_dev
    depends_on: 
      - koth
  certbot:
    image: certbot/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot