version: '3'
services:
  koth:
    restart: always
    image: $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$CURRENT_BRANCH
    ports:
      - "8000:8000"
    environment: 
      - EXT_SECRET=$EXT_SECRET
      - EXT_CLIENT_ID=$EXT_CLIENT_ID
      - EXT_OWNER_ID=$EXT_OWNER_ID
  nginx:
    image: nginx:1.15-alpine
    ports:
      - "8081:8081"
      - "80:80"
      - "443:443"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on: 
      - koth
  certbot:
    image: certbot/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.docker/config.json:/config.json
      - ~/.aws/:/.aws
      - helper:/go/bin
      - /usr/bin/:/usr/bin/
      - /bin/:/bin/
    environment:
      - AWS_REGION=us-east-2 # this is required for docker-credential-ecr-login
      - HOME=/
      - PATH=$PATH:/usr/bin
    command: --interval 60
volumes:
  helper:
    external: true
